### ISSUE TITLE
 컴파일러

### ISSUE THREAD

**Issue by limehee** [KGU-C-Lab/clab-server#139]
### Describe

스터디 진행 중 발생하는 과제 또는 시험 등을 보다 쉽게 제출하고 채점, 관리할 수 있도록 합니다.
백준, 프로그래머스 등의 형식의 같이 사용자로부터 코드를 제출받고, 서버에서 채점을 하여 결과를 제공합니다.

### Tasks

- [ ] 코드 실행을 위한 격리된 환경(컨테이너, VM 등) 구축
- [ ] 채점 알고리즘
- [ ] 리소스 제한(메모리, CPU, 네트워크 접근 등)
- [ ] 단위/통합 테스트
