### ISSUE TITLE
코드 리팩토링

### ISSUE THREAD

**Issue by mingmingmon** [KGU-C-Lab/clab-server#276]
### Describe

DDD(Domain-Driven Design)를 적용하고 기존 비효율적인 코드를 수정합니다.

### Tasks

리팩토링 목록
- [x] accuse
- - [x] accuseService의 createAccuse 에서 요청 유효 함수화
- - [x] notification request dto 생성 대신 notification의 of 메소드 오버로딩
- - [x] board, comment, review 존재 여부 함수를 각각 대응하는 service에 생성 후 활용
- - [x] 신고 내역 조회, 유형/상태별 신고 내역 조회 API 통합 및 QueryDSL을 통해 처리하도록 변경
- - [x] 신고하기 및 신고 상태 변경 API 로직 개선
- [x] activityGroupAdmin
- - [x] 일부 로직 도메인 이전
- [x] activityGroupBoard
- - [x] 활동 그룹 게시판 생성 일부 로직 도메인으로 이전 및 메소드 분리
- - [x] 활동 그룹 게시판 계층 구조적 조회 일부 로직 도메인으로 이전
- - [x] 나의 제출 과제 및 피드백 조회, 활동 그룹 게시판 수정/삭제 로직 최적화 및 도메인 이전
- - [x] getChildBoards() 로직 간소화
- - [x] validateParentBoard() 로직 최적화
- [x] activityGroupMember
- - [x] 일부 로직을 도메인으로 이전
- - [x] 활동 전체 목록 조회 최적화
- - [x] 활동 상태별 조회 최적화
- [x] activityGroupReport
- - [x] 기능별 메소드 분리
- [x] Attendance
- - [x] static 변수 및 불필요 메소드 제거
- - [x] 기능별 메소드 분리
- [x] activityPhoto
- - [x] 활동 사진 목록 조회, 공개된 활동 사진 목록 조회 API 통합 및 QueryDSL을 통해 처리하도록 변경
- - [x] 활동 사진 등록 로직 개선
- - [x] 활동 사진 고정/해제 로직 도메인으로 이전
- - [x] 업로드 파일 가져오는 로직 메소드로 분리
- [x] application
- - [x] controller, service의 메소드 이름 수정
- - [x] 지원자 목록 조회 repository 코드 분리 및 path명 변경
- - [x] 동아리 지원 API 로직 간소화 및 일부 로직 도메인으로 이전
- - [x] 합격 여부 조회 로직 개선
- [x] award
- - [x] 수상 이력 등록 로직 간소화
- - [x] 수상 이력 검색 로직을 QueryDSL을 통해 처리하도록 변경
- - [x] 수상 이력 수정/삭제 권한 로직을 도메인으로 이전
- [x] blacklistIp
- - [x] 블랙리스트 IP 추가 로직 개선
- [x] blog
- - [x] 블로그 포스트 목록 조회, 블로그 포스트 검색 통합 및 QueryDSL을 통해 처리하도록 변경
- - [x] 일부 서비스 로직을 도메인으로 이전
- [x] board
- - [x] 일부 서비스 로직을 도메인으로 이전
- [x] book
- - [x] 도서 목록, 도서 검색 API 통합 및 QueryDSL을 통해 처리하도록 변경
- - [x] 도서 조회 공통 로직 메소드로 분리
- [x] bookLoanRecord
- - [x] 도서 대출 내역 조회 API 로직을 QueryDSL을 통해 처리하도록 변경
- - [x] 서비스 로직 일부를 도메인으로 이전
- [x] comment
- - [x] 댓글 생성 로직 간소화
- - [x] 댓글 좋아요 및 소유자 확인 로직을 도메인으로 이전
- - [x] 로직 기능별 모듈화
- - [x] 댓글 수정/삭제 권한 로직을 도메인으로 이전
- [x] donation
- - [x] 커스텀 예외처리 활용
- - [x] 후원 정보, 후원 검색 API 통합 및 QueryDSL을 통해 처리하도록 변경
- - [x] 후원 생성 로직 간소화 및 수정/삭제 조건 검사 로직 메소드로 분리
- [x] jobPosting
- - [x] 채용 공고 목록 조회, 채용 공고 검색 API 통합 및 QueryDSL을 통해 처리하도록 변경
- - [x] 채용 공고 등록 로직 개선
- [x] login
- - [x] AccountLockInfo
- - - [x] Entity 생성 로직 변경 및 및 밴 설정/해제 로직을 도메인으로 옮김
- - - [x] 계정 잠금 관리 메소드 개선
- - - [x] 로그인 실패에 대한 관리 일부를 도메인에서 하도록 변경
- - [x] Login
- - - [x] 멤버 로그인 로직을 기능별로 모듈화
- - - [x] TOTP 인증 로직을 기능별로 모듈화
- - - [x] 토큰 재발급 로직을 기능별로 모듈화
- - [x] Authenticator
- - - [x] 변수명 변경 및 인스턴스 생성/저장 로직 메소드로 분리
- - - [x] GoogleAuthenticator를 스프링 빈으로 등록하여 주입받도록 변경
- - [x] LoginAttemptLog
- - - [x] LoginAttemptLog 생성 로직 간소화
- - [x] RedisToken
- - - [x] RedisToken 생성 로직 간소화
- - - [x] IP 비교 메소드 도메인으로 이전
- [x] member
- - [x] 클라우드 관련 로직 및 메소드 분리
- - [x] 멤버 유니크 조건 검사를 별도의 메소드로 분리
- - [x] 비밀번호 생성 로직 verificationCodeService로 이동
- - [x] 모든 멤버 정보 조회, 멤버 검색 API 통합 및 QueryDSL을 통해 처리하도록 변경
- - [x] 일부 로직 도메인으로 이전
- [x] membershipFee
- - [x] 회비 정보 조회, 회비 검색 API 통합 및 QueryDSL을 통해 처리하도록 변경
- - [x] toEntity 로직 간소화
- - [x] 회비 수정/삭제 권한 로직을 도메인으로 이전
- [x] news
- - [x] 뉴스 목록 조회, 뉴스 검색 API 통합 및 QueryDSL을 통해 처리하도록 변경
- - [x] 뉴스 파일 등록 로직 메소드로 분리
- [x] notification
- - [x] 알림 생성 로직 분리
- - [x] 알림 전송 공통 로직을 메소드로 분리
- - [x] 알림 삭제 권한 로직을 도메인으로 이전
- [x] position
- - [x] 연도/직책별 목록 조회 API 로직을 QueryDSL을 통해 처리하도록 변경
- [x] product
- - [x] 서비스 조회, 서비스 검색 API 통합 및 QueryDSL을 통해 처리하도록 변경
- [x] recruitment
- - [x] 미사용 변수 제거
- [x] review
- - [x] 알림 전송 로직 변경
- - [x] 생성 조건 검사를 별도의 메소드로 분리
- - [x] 공개 리뷰 목록, 리뷰 검색 API 통합 및 QueryDSL을 통해 처리하도록 변경
- - [x] 리뷰 수정, 리뷰 공개/비공개 API 통합
- - [x] 리뷰 조건 검사 및 알림 전송 로직을 메소드로 분리
- - [x] 일부 로직을 도메인으로 이전
- [x] schedule
- - [x] toEntity 로직 간소화
- - [x] 기능별 메소드 분리
- - [x] 일정 조회 로직을 QueryDSL을 통해 처리하도록 변경
- - [x] 일정 조회시 LocalDate를 입력받도록 변경
- - [x] 일부 로직을 도메인으로 이전
- [x] sharedAccount
- - [x] 공동계정 생성 로직 간소화
- [x] SharedAccountUsage
- - [x] 공동 계정 이용 신청 로직 일부를 도메인으로 이전
- - [x] 조건 검사 메소드 분리 세분화
- - [x] 공동 계정 이용 상태 변경 로직 일부를 도메인으로 이전
- - [x] 기능별 메소드 분리 
- [x] workExperience
- - [x] 권한 검사 로직 도메인으로 이전
- [x] email
- - [x] 이메일 전송 로직 분리
- [x] verificationCode
- - [x] 일부 로직 도메인 이전
- [x] RedisIpAccessMonitor
- - [x] 일부 로직 도메인 이전
- [x] validation
- - [x] 컨트롤러에서 예외를 추가로 처리하지 않기로 변경
- - [x] 유효성 검사 로그 상세화
- - [x] Entity, DTO 도메인 지식 구분 및 제약조건 재설정
- - [x] Controller + Service에서 유효성 검사하도록 변경
- [x] 조회 API Transactional readOnly 설정
- [x] 수정일자 칼럼명 updatedAt 통일 및 갱신 누락 수정
- [x] 객체 변환 로직으로부터 도메인 격리
- [x] BaseEntity를 적용하여 생성 및 수정일자 관리
- [x] 파일 업로드 비즈니스 / 저장소 접근 로직 분리
