### ISSUE TITLE
게시글 및 댓글 반환 정보 수정

### ISSUE THREAD

**Issue by limehee** [KGU-C-Lab/clab-server#334]
### Describe

클라이언트에서 게시글, 댓글과 관련한 요청을 보낸 후 정보를 재요청할 수 있도록 반환정보를 변경합니다.
댓글이 작성된 일자를 추가로 반환합니다.

### Tasks

- [x] 게시글 생성, 수정, 삭제시 삭제된 게시글의 카테고리가 반환되도록 변경
- [x] 댓글 생성, 수정, 삭제시 게시글의 id를 반환하도록 변경
- [x] 댓글 응답 정보에 생성일자(createdAt) 추가
