### ISSUE TITLE
슬랙 메시지 개선

### ISSUE THREAD

**Issue by limehee** [KGU-C-Lab/clab-server#346]
### Describe

일부 슬랙 메시지에 대한 개선을 목표로 합니다.
개선 대상은 다음과 같습니다.
1. 로그인에 대한 보안 경고
2. 템플릿

### Tasks

- [x] 중복 로그인 및 지속적인 로그인 실패에 대한 경고 대상을 관리자 이상의 멤버로 제한
- [x] 중복 로그인 및 지속적인 로그인 실패에 대한 사용자의 정보를 메시지에 표기할 수 있도록 개선
- [x] 미리보기에서 제목 확인이 가능하도록 개선
