### ISSUE TITLE
모니터링 시스템 도입

### ISSUE THREAD

**Issue by limehee** [KGU-C-Lab/clab-server#348]
### Describe

모니터링 시스템 도입은 다음의 목표를 가집니다.
1. 로그를 중앙에서 관리하고 시각화하여 보다 쉽게 접근하고 활용할 수 있도록 합니다.
2. 사용자의 행동 패턴을 분석합니다.
3. 시스템 상태를 실시간으로 모니터링하고, 문제 발생 시 빠르게 대응할 수 있도록 합니다.
4. 시스템 로그를 통해 보안 이벤트를 모니터링하고 감사 로그를 관리합니다.

---

Actuator 접근 제어를 위해, 화이트리스트 기능이 보다 범용성있게 작동할 수 있도록 수정하였습니다.

### Tasks

- [x] Logback 설정
- [x] Actuator 설정
- [x] Actuator 접근 제어
- [x] 서버 메트릭 수집(Prometheus, Node Exporter)
- [x] 로그 수집(Promtail, Loki)
- [x] 시각화(Grafana)
- [x] 도메인 설정
