### ISSUE TITLE
젠킨스 슬랙 알림 개선

### ISSUE THREAD

**Issue by limehee** [KGU-C-Lab/clab-server#370]
### Describe

[1]
서버 환경에 따라 Attachment color를 설정하여 알림을 구분할 수 있도록 합니다.

[2]
빌드 성공/실패 여부를 보다 쉽게 구분하기 위해 메시지의 색상을 부여합니다.

[3]
Git 변경 사항을 출력합니다.

### Tasks

- [x] Slack Message에 Attachment 추가
- [x] Jenkins Credentials에 슬랙 메시지 색상 추가
- [x] Git 변경 사항을 가져와 출력하도록 함
