### ISSUE TITLE
젠킨스 빌드 메시지 개선

### ISSUE THREAD

**Issue by limehee** [KGU-C-Lab/clab-server#381]
### Describe

젠킨스 빌드 성공/실패 시 발생하는 메시지의 포맷을 표준화합니다.
이 작업은 Spring 애플리케이션에서 전송하는 메시지와의 포맷 통일과 보다 쉬운 로그 확인을 목표로 합니다.

### Tasks

- [x] Slack Block Kit을 이용한 빌드 메시지 전송
- [x] Job, Console Output 버튼 추가
- [x] 페이로드를 JSON 객체로 정의하여 쉽게 변경 가능하도록 함

### ETC
빌드 실패시 추가적인 정보를 메시지로 보내려 했으나, 젠킨스에서 전역 변수로 지원하지 않아 제외함.
[Global Variable Reference](https://www.jenkins.io/doc/book/pipeline/jenkinsfile/#using-environment-variables)
